# Site settings
title: m.Abdelsattar
email: m.abdelsattarahmed@gmail.com
url: https://abdelsattar.github.io
description: "An Android developer personal website Name Mohammed Abd EL-Sattar certified As Android developer by Google-Udacity and MCIT Scholarship now aim to apply material design in every app he make and follow all guidelines by Google to generate Awesome app in UI and Performance."
skills: "Android Developer - Problem Solver"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: mAbdelsattar
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/abdelsattar512
  - title: facebook
    url: https://www.facebook.com/m.abdelsattar0
  - title: github
    url: http://github.com/abdelsattar

# Postal address (add as many lines as necessary)
address:
  - line: 10 – EL Moawen St,
  - line: Omranya, Giza ,Egypt

# Credits content
credits: 'This is a free themes and cutsomized by @Abdelsattar and free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
